name: Crawling
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */2 * * *"

jobs:
  crawling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install
        run: npm i

      - name: Crawling
        run: npm start

      - name: Upload
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: data
