on: 
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 1 1-12 *'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.1'
      - name: NPM Install
        run: |
          npm i -g typescript
          npm install
      - name: Run script
        run: |
          npm start
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: data # The folder the action should deploy.
